{"uuid": "92d74528-e5d2-4419-a8fd-ccea4a868b1e", "counter": 6, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub\"}\u001b[0m", "start_line": 6, "end_line": 7, "runner_ident": "6b49e8cf-566d-4d10-9729-fdffdc165137", "event": "runner_on_failed", "pid": 10481, "created": "2020-11-30T19:28:12.906153", "parent_uuid": "50e085c0-7515-8f91-516a-000000000008", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml", "playbook_uuid": "c0a09a3d-2adc-4b02-83b7-cf7c2b08fe78", "play": "Prepare keys for root (as 'pi', connect with password)", "play_uuid": "50e085c0-7515-8f91-516a-000000000006", "play_pattern": "all", "task": "Set authorized_key for root user", "task_uuid": "50e085c0-7515-8f91-516a-000000000008", "task_action": "authorized_key", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml:16", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub", "_ansible_no_log": false}, "start": "2020-11-30T19:28:12.887071", "end": "2020-11-30T19:28:12.906036", "duration": 0.018965, "ignore_errors": null, "event_loop": null, "uuid": "92d74528-e5d2-4419-a8fd-ccea4a868b1e"}}