{"uuid": "9ab8f9fa-6653-467f-95bd-655f7f7ce52a", "counter": 6, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub\"}\u001b[0m", "start_line": 6, "end_line": 7, "runner_ident": "bc248a70-4436-4733-8648-6304ed7ba71d", "event": "runner_on_failed", "pid": 10677, "created": "2020-11-30T19:31:48.186456", "parent_uuid": "50e085c0-7515-3e3f-68aa-000000000008", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml", "playbook_uuid": "f9c240aa-4987-454d-958b-b4a3de829f12", "play": "Prepare keys for root (as 'pi', connect with password)", "play_uuid": "50e085c0-7515-3e3f-68aa-000000000006", "play_pattern": "all", "task": "Set authorized_key for root user", "task_uuid": "50e085c0-7515-3e3f-68aa-000000000008", "task_action": "authorized_key", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml:16", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub", "_ansible_no_log": false}, "start": "2020-11-30T19:31:48.167121", "end": "2020-11-30T19:31:48.186325", "duration": 0.019204, "ignore_errors": null, "event_loop": null, "uuid": "9ab8f9fa-6653-467f-95bd-655f7f7ce52a"}}