{"event": "verbose", "uuid": "35f19fdc-3fcf-47ab-b783-74efbcb979fe", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml': line 70, column 7, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "ba68d767-1527-478d-9ef9-19a8076d09cf"}