{"uuid": "9d73f9e0-8547-4079-8e34-70579e07dbf2", "counter": 6, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/rsa.pub\"}\u001b[0m", "start_line": 6, "end_line": 7, "runner_ident": "4e7f8977-222a-4b5a-894e-4f566fb6d21b", "event": "runner_on_failed", "pid": 4236, "created": "2020-11-30T09:05:38.867700", "parent_uuid": "50e085c0-7515-da9b-b360-000000000008", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml", "playbook_uuid": "6420f612-815b-475f-ae82-5118b1bd0090", "play": "Prepare keys for root (as 'pi', connect with password)", "play_uuid": "50e085c0-7515-da9b-b360-000000000006", "play_pattern": "all", "task": "Set authorized_key for root user", "task_uuid": "50e085c0-7515-da9b-b360-000000000008", "task_action": "authorized_key", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml:13", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/rsa.pub", "_ansible_no_log": false}, "start": "2020-11-30T09:05:38.846984", "end": "2020-11-30T09:05:38.867586", "duration": 0.020602, "ignore_errors": null, "event_loop": null, "uuid": "9d73f9e0-8547-4079-8e34-70579e07dbf2"}}