{"uuid": "d4f5475e-8766-4650-a43c-e268f1c2e993", "counter": 6, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/id_rsa.pub\"}\u001b[0m", "start_line": 6, "end_line": 7, "runner_ident": "4e7f8977-222a-4b5a-894e-4f566fb6d21b", "event": "runner_on_failed", "pid": 4301, "created": "2020-11-30T09:06:18.649473", "parent_uuid": "50e085c0-7515-127f-d6c9-000000000008", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml", "playbook_uuid": "3ca4bf59-0754-48fa-a664-fe7e1d7aaa3a", "play": "Prepare keys for root (as 'pi', connect with password)", "play_uuid": "50e085c0-7515-127f-d6c9-000000000006", "play_pattern": "all", "task": "Set authorized_key for root user", "task_uuid": "50e085c0-7515-127f-d6c9-000000000008", "task_action": "authorized_key", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml:13", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/id_rsa.pub", "_ansible_no_log": false}, "start": "2020-11-30T09:06:18.629912", "end": "2020-11-30T09:06:18.649342", "duration": 0.01943, "ignore_errors": null, "event_loop": null, "uuid": "d4f5475e-8766-4650-a43c-e268f1c2e993"}}