{"uuid": "ab7bb57b-5d64-41de-b667-8fe4d7ba40e2", "counter": 6, "stdout": "\u001b[0;31mfatal: [192.168.1.30]: FAILED! => {\"msg\": \"An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub\"}\u001b[0m", "start_line": 6, "end_line": 7, "runner_ident": "17083232-bf3f-4146-bd70-86b6e46faf44", "event": "runner_on_failed", "pid": 10251, "created": "2020-11-30T19:24:29.524414", "parent_uuid": "50e085c0-7515-2ca7-7ea4-000000000008", "event_data": {"playbook": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml", "playbook_uuid": "276b1212-5a4c-4295-b46d-9d5ef24a0ea2", "play": "Prepare keys for root (as 'pi', connect with password)", "play_uuid": "50e085c0-7515-2ca7-7ea4-000000000006", "play_pattern": "all", "task": "Set authorized_key for root user", "task_uuid": "50e085c0-7515-2ca7-7ea4-000000000008", "task_action": "authorized_key", "task_args": "", "task_path": "/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml:16", "host": "192.168.1.30", "remote_addr": "192.168.1.30", "res": {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/zanzocam_id_rsa.pub", "_ansible_no_log": false}, "start": "2020-11-30T19:24:29.504756", "end": "2020-11-30T19:24:29.524298", "duration": 0.019542, "ignore_errors": null, "event_loop": null, "uuid": "ab7bb57b-5d64-41de-b667-8fe4d7ba40e2"}}