{"event": "verbose", "uuid": "927bf178-83af-4f88-9954-9947ec7af601", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/s/projects/raspicam/remotecam/files/setup/ansible/rpi_custom_user.yml': line 70, column 7, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "26d7d4bd-da13-4f3a-8607-99ab431fd164"}